### ISSUE TITLE
comparative genomics: assembly.md 

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/BioinfTraining#107]
error 404 - first link (practicals) "https://github.com/karinlag/INF-BIOx121/tree/2017/Assembly/practicals"
cannot find it in your github for the new course (maybe renamed?).... so not sure you wanted to redirect to. 

**Can you add that?** -> changes in this file will go in the evfi-assembly branch until its ready to merge (will have to be able to go through material first to finish corrections)

+NB changed name course to new course, + added link (so we can view slides and recommended literature).

**Comment by karinlag** [comment]
Not sure what is wrong here... I tried looking at the course pages, but I can't find the missing link that you seem to be referring to? Am I misunderstanding something?

**Comment by evezeyl** [comment]
its in assembly.md, the link I am refering to that does not redirect to anything is: <https://github.com/karinlag/INF-BIOx121/tree/2017/Assembly/practicals>, its the first link in assembly.md: _Link to the relevant pages_

I guess you wanted to redirect to assembly using velvet: 
I found that afterwards in 2018 Uio course: <https://github.com/arvindsundaram/IN-BIOSx000/blob/2018/Assembly/practicals/02_Assembly_using_velvet.md>
should I redirect in there?

**Comment by evezeyl** [comment]
ok, think found it - moved to arvindsundaram/IN-BIOSx000 -> linked there. Clossing issue
