### ISSUE TITLE
Unix Commands for Biologists/Bioinformaticians - grep/awk/sed

### ISSUE THREAD

**Issue by ajkarloss** [NorwegianVeterinaryInstitute/BioinfTraining#108]
**This manual is to teach/introduce Biologists to the world of grep/awk/sed commands** 

**Input files at Abel** 
/projects/nn9305k/Bioinfo_Training_Files/

**grep command** 

Number of sequences in fasta file
`grep ">" Seq.fasta`
`grep -c "^>" Seq.fasta`

Remove blank lines
`grep -v "^$" Annotation.gff3`

Picking gene names with "ignore case"
`grep -i 'XP_014064670' Annotation.gff3`

Pick only the exact matching word
`grep -w 'N-methyltransferase' Annotation.gff3`
`grep -A 2 -w 'N-methyltransferase' Annotation.gff3`
`grep -B 2 -w 'N-methyltransferase' Annotation.gff3`

Inverted grep
`grep -v 'Jeevan' Names.txt`

`grep  -i 'TATTTTAGATTTATT' Seq.fasta`

`grep --color "T..TTTAGATT..TT" Seq.fasta`

**awk command**
`awk '{print $4}' Annotation.gff3`
`awk -F ";" '{print $1}' Annotation.gff3`
`awk '$3 == "CDS" {print}' Annotation.gff3`
`awk '$4 >100000 && $5 <2000000 {print}' Annotation.gff3` 

 Print the last field of each line.
awk '{ print $NF }' Annotation.gff3

Print only the lines that match a regular expression “/regex/” (emulates “grep”).
awk '/regex/' filename
    This one-liner uses a regular expression “/regex/” as a pattern. If the current line matches the regex, it evaluates to true, and Awk prints the line (remember that missing action statement is equal to “{ print }” that prints the whole line).

Print only the lines that do not match a regular expression “/regex/” (emulates “grep -v”).
awk '!/regex/' filename

**sed command**
sed 's/NC_027300.1/Chr2/g' Annotation.gff3

sed 's/NC_027300.1/Chr2/30g' Annotation.gff3
This will replace unix to linux from line 3

Replacing string on a specific line number : You can restrict the sed command to replace the string on a specific line number. An example is
$sed '3 s/unix/linux/' Annotation.gff3

Replacing string on a range of lines : You can specify a range of line numbers to the sed command for replacing a string.
$sed '1,3 s/unix/linux/' Annotation.gff3

**Comment by karinlag** [comment]
Closing, since we are done with this. You might create a md doc from this instead and incorporate?
