### ISSUE TITLE
Check introduction.md regarding instructions for tomorrow

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/BioinfTraining#15]
Can you look through the website, specifically the introduction page which contains instructions for tomorrow and see if things look good?

**Comment by arvindsundaram** [comment]
Instructions for tomorrow looks good. I have made some minor changes and have requested a pull request. 
I have gone through the step-by-step instructions by Thomas for Biolinux installation and works perfectly well!

**Comment by Thomieh73** [comment]
Looks good to me!
