### ISSUE TITLE
Create how-to for installing biolinux in a virtualbox

### ISSUE THREAD

**Issue by karinlag** [NorwegianVeterinaryInstitute/BioinfTraining#2]
We need a how-to for setting up a virtualmachine with biolinux in it. I have one of the machines we will be using, are there settings on the computer we need to check out? I think there's something regarding some (possibly in bios) settings that need to be changed...

**Comment by Thomieh73** [comment]
I have created a markdown file called: How_to_virtual_machine_set-up.md

I suggest to delete the file: How_to_virtual_machine_set-up.txt
since it has an incorrect extension.

**Comment by Thomieh73** [comment]
I have done so.
