### ISSUE TITLE
Definition adapter files?  I am not sure I understand + smaller issue

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/BioinfTraining#89]
Q1: 
In file: "working_with_hpc.md"
What are adapter files?
Found in line: 
3. use the knowledge gained from the README file to figure out where adapter files are stored on abel.

Q2:
There is a temporary file: working_with_hpc.md~ in git - not sure if you want to keep it

**Comment by karinlag** [comment]
Adapter files are related to trimming of sequence files. These might remain in the sequence data, and need to be removed from the sequences. 

And no, I do not want to keep temp files :)

**Comment by evezeyl** [comment]
Well, long time ago - and explanation ok, so closing
