### ISSUE TITLE
? moving samplesfiles in Abel + new_user.txt checked

### ISSUE THREAD

**Issue by evezeyl** [NorwegianVeterinaryInstitute/BioinfTraining#99]
Was wondering if directory `samplefiles` should be moved from `work` to `project`. Would be more logical - as templates will be required in `project` now.

- NB: Done: checked paths in new_user.txt (in samplefiles) -> copy corrected = `/projects/nn9305k/home/evezeyl/for_karin/new_user.txt_path_checked`
- README in checked - >  path ok

**Comment by karinlag** [comment]
Hmm.... @Thomieh73, @arvindsundaram and @ajkarloss , do you have opinions here? I would be tempted to have the data related templates in projects (but then under the name templates), while scripts and slurm things stay on work?

**Comment by Thomieh73** [comment]
Why leave the example files for scripts and slurm on work? Aren's those templates as well?

**Comment by karinlag** [comment]
I keep coming back to the separation of storage "stuff" and compute "stuff". I am wondering if it becomes easier to help people separate that if we also separate the template files for the two. However, that might just be completely in my head.

@evezeyl do you have any opinions? You've been trying to figure out all of these things most recently of all of us :slightly_smiling_face:

**Comment by Thomieh73** [comment]
I think it is easiest when all template files are in the same location. I am not understanding what you mean with data related templates... any example you can give?

**Comment by karinlag** [comment]
So, here I am thinking of the data README files and such. However, those will now anyhow be living in the datasets directory, so possibly this point is moot anyhow.

**Comment by Thomieh73** [comment]
Okay, those files. I think we could at least save those in a folder called Templates. I find the location of that folder on project easier than work, because scripts need to be stored in the folder next to the data that is analyzed. Does that make sense?

**Comment by karinlag** [comment]
Yep that it does :slightly_smiling_face: 

Thus I think we should go for this unless anybody else comes up with anything we've forgotten that influences this.

**Comment by Thomieh73** [comment]
Agreed

**Comment by karinlag** [comment]
This is now redundant. Closing.
